#!/bin/bash

export DJB_FORCED_HOSTNAME=127.0.0.1:8081
export SAFDEF_LOG_LEVEL=debug;
# emerg alert crit err warning notice info debug


VALGRIND=$1

SERVER="server/djb run"

if [ -n "$VALGRIND" ]
then
valgrind --leak-check=yes  --dsymutil=yes  ${SERVER}
else
${SERVER}
fi

#--num-callers=30 -v --db-attach=yes --gen-suppressions=all --track-fds=yes