CHROME=/Applications/Chromium.app/Contents/MacOS/Chromium

all:  pack

pack:
	./pack.bash jumpbox_plugin_chrome jumpbox_plugin_chrome.pem
#	${CHROME} --pack-extension=jumpbox_plugin_chrome --pack-extension-key=jumpbox_plugin_chrome.pem


